spring.application.name=TriatlonBackend

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/triatlon_db
spring.datasource.username=root
spring.datasource.password= 

# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080


#CONFIGURACI\u00d3N PARA EL ENVIO DEL CORREO,
#ESPECIFICAMENTE PARA LA DISTRIBUCI\u00d3N DE CORREOS GMAIL

#Cuenta emisora del correo 
spring.mail.username=atjuan.vina7@gmail.com
#Contrase\u00f1a de aplicaci\u00f3n
spring.mail.password=noqzzeqkacingzjz
#La direcci\u00f3n del servidor (gmail)
spring.mail.host=smtp.gmail.com
#Puerto de conexi\u00f3n (el estandar)
spring.mail.port=587
#Activa la autenticaci\u00f3n
spring.mail.properties.mail.smtp.auth=true
#Cifrado TLS (establece una conexi\u00f3n encriptada)
spring.mail.properties.mail.smtp.starttls.enable=true


